import { extend } from '../i18n';

// Sürüm 1.2: uzay dünyaları, yeni meteorlar, bosslar, yetenekler, mağaza ve ödüllü videolar

extend('tr', {
  'w.combo.200': 'ŞEHİR SENİNLE!',
  'menu.shop': 'Mağaza',
  'menu.skills': 'Yetenek',

  'atm.orion': 'Orion Bulutsusu',
  'atm.orion.d': 'Avcı takımyıldızının kuşağı altında renkli bir yıldız doğumevi.',
  'atm.saturn': 'Satürn Halkaları',
  'atm.saturn.d': 'Dev halkaların gölgesinde buz kristalleri yağar.',
  'atm.horizon': 'Olay Ufku',
  'atm.horizon.d': 'Işığı bile yutan kara delik; hayaletler çoğalır.',
  'atm.nova': 'Süpernova',
  'atm.nova.d': 'Patlayan bir yıldızın ışığında son ve sonsuz dünya.',

  // meteorlar ve bosslar
  'w.frozen': 'DONDU!',
  'w.shieldBreak': 'KRİSTAL KIRILDI',
  'w.shielded': 'KALKAN!',
  'w.twinDown': 'BİR İKİZ DÜŞTÜ!',
  'w.secondWind': 'İKİNCİ NEFES!',
  'w.bossDown.0': 'KAYA TİTANI DÜŞTÜ!',
  'w.bossDown.1': 'KRALİÇE DÜŞTÜ!',
  'w.bossDown.2': 'KALE YIKILDI!',
  'w.bossDown.3': 'TEKİLLİK SÖNDÜ!',
  'w.bossDown.4': 'İKİZLER DÜŞTÜ!',
  'boss.0': 'KAYA TİTANI',
  'boss.0.d': 'Sektirdiğin meteorları ona çarptır',
  'boss.1': 'KUYRUKLU KRALİÇE',
  'boss.1.d': 'Hızlı süzülür, kuyruklu yıldız yağdırır',
  'boss.2': 'BUZ KALESİ',
  'boss.2.d': 'Önce dönen kristalleri kır',
  'boss.3': 'TEKİLLİK',
  'boss.3.d': 'Halka daralınca çizgilerin kırılır!',
  'boss.4': 'İKİZ YILDIZLAR',
  'boss.4.d': 'İkisini de düşür, biri kalırsa öfkelenir',

  // yetenekler
  'hud.skillReady': 'HAZIR',
  'skill.nova': 'YILDIZ PATLAMASI',
  'skill.nova.d': 'Şehirden yükselen şok dalgası ekrandaki tüm meteorları yok eder, boss\'a ağır hasar verir.',
  'skill.warp': 'ZAMAN KIRILMASI',
  'skill.warp.d': 'Meteorlar 5 saniye boyunca neredeyse durur, mürekkebin 2,5 kat hızlı dolar.',
  'skill.aegis': 'AEGIS KALKANI',
  'skill.aegis.d': '7 saniye boyunca şehrin üstünde bir kubbe: çarpan meteorlar mürekkebe dönüp geri fırlar.',
  'skill.starfall': 'YILDIZ YAĞMURU',
  'skill.starfall.d': 'Şehirden 12 güdümlü yıldız fırlar, düşmanları ve boss\'u avlar.',
  'skills.title': 'Yetenekler',
  'skills.desc': 'Meteor patlattıkça yetenek halkası dolar. Dolunca sağ alttaki düğmeye dokun. Bir yetenek takabilirsin.',
  'skills.on': 'Takılı',
  'skills.equip': 'Tak',

  // kartlar
  'upg.leech.d': 'Patlattığın meteorlardan %80 fazla mürekkep.',
  'upg.midas.d': 'Puan ve altın kazancı +%40.',
  'upg.lucky': 'Şans Yıldızı',
  'upg.lucky.d': 'Altın meteorlar daha sık gelir ve +3 altın verir.',
  'upg.ink_surge': 'Mürekkep Dalgası',
  'upg.ink_surge.d': 'Her 10 komboda +{v} mürekkep.',
  'upg.magnet': 'Mıknatıs Uç',
  'upg.magnet.d': 'Sektirdiğin meteorlar en yakın düşmana doğru kıvrılır.',
  'upg.frost': 'Kırağı',
  'upg.frost.d': 'Her sekme çevresindeki düşmanları {v} sn yavaşlatır.',
  'upg.ricochet': 'Sekme Ustası',
  'upg.ricochet.d': 'Sektirdiğin meteorlar tavandan {v} kez geri döner.',
  'upg.overcharge': 'Aşırı Yük',
  'upg.overcharge.d': 'Yetenek halkası %{v} daha hızlı dolar.',
  'upg.second_wind': 'İkinci Nefes',
  'upg.second_wind.d': 'Bir mahalle yıkılınca mürekkep dolar, zaman bir an yavaşlar.',
  'upg.guardian': 'Koruyucu Uydu',
  'upg.guardian.d': 'Şehrin üstünde dönen uydu her {v} sn\'de en alçak meteoru lazerle vurur.',

  // devam
  'revive.desc': 'Üç mahalleyi yeniden kur, kaldığın yerden devam et.',
  'revive.video': 'VİDEO İZLE · DEVAM ET',
  'revive.free': 'DEVAM ET · REKLAMSIZ',

  // oyun sonu / hediye
  'over.double': 'Video izle, altınları ikiye katla (+{n})',
  'gift.claim2x': '2 KAT AL · {n}',

  // demo reklam
  'ad.tag': 'REKLAM',
  'ad.title': 'Ödüllü video',
  'ad.desc': 'Uygulamada burada kısa bir video oynar. Bu önizlemede temsili gösterilir.',
  'ad.close': 'Ödülü al',

  // mağaza
  'shop.title': 'Mağaza',
  'shop.coins': 'Altın paketleri',
  'shop.popular': 'EN POPÜLER',
  'shop.best': 'EN İYİ DEĞER',
  'shop.once': 'TEK SEFER',
  'shop.starter': 'Başlangıç Paketi',
  'shop.starterDesc': '{n} altın + Zaman Kırılması yeteneği. Yeni oyunculara özel.',
  'shop.noads': 'Reklamsız',
  'shop.noadsDesc': 'Video izlemeden tüm ödüller anında: devam, 2 kat altın, hediyeler.',
  'shop.noadsOwned': 'Etkin. Ödüller video izlemeden anında gelir.',
  'shop.free': 'Ücretsiz {n} altın',
  'shop.freeLeft': 'Bugün {n}/{max} hak kaldı',
  'shop.watch': 'İzle',
  'shop.restore': 'Satın alımları geri yükle',
  'shop.demo': 'Önizleme: gerçek ödeme alınmaz, paketler denemek için anında eklenir.',

  // bildirimler
  'toast.noAds': 'Reklamsız: ödül anında!',
  'toast.adFail': 'Şu an video yok, biraz sonra dene',
  'toast.adSkip': 'Ödül için videoyu sonuna kadar izle',
  'toast.storeOff': 'Mağaza şu an kullanılamıyor',
  'toast.buyFail': 'Satın alma tamamlanamadı',
  'toast.demoBuy': 'Önizleme: ödeme alınmadı',
  'toast.noAdsOn': 'Reklamsız etkin. Teşekkürler!',
  'toast.bought': '+{n} altın',
  'toast.restored': 'Satın alımlar geri yüklendi',
  'toast.nothing': 'Geri yüklenecek satın alım yok',
  'toast.needCoins': 'Yeterli altın yok',
});

extend('en', {
  'w.combo.200': 'THE CITY IS WITH YOU!',
  'menu.shop': 'Shop',
  'menu.skills': 'Skill',

  'atm.orion': 'Orion Nebula',
  'atm.orion.d': "A colourful stellar nursery under the Hunter's belt.",
  'atm.saturn': "Saturn's Rings",
  'atm.saturn.d': 'Ice crystals fall in the shadow of the giant rings.',
  'atm.horizon': 'Event Horizon',
  'atm.horizon.d': 'A black hole that swallows even light; phantoms multiply.',
  'atm.nova': 'Supernova',
  'atm.nova.d': 'The last, endless world, lit by an exploding star.',

  'w.frozen': 'FROZEN!',
  'w.shieldBreak': 'CRYSTAL BROKEN',
  'w.shielded': 'SHIELDED!',
  'w.twinDown': 'ONE TWIN DOWN!',
  'w.secondWind': 'SECOND WIND!',
  'w.bossDown.0': 'ROCK TITAN DOWN!',
  'w.bossDown.1': 'QUEEN DOWN!',
  'w.bossDown.2': 'CITADEL SHATTERED!',
  'w.bossDown.3': 'SINGULARITY COLLAPSED!',
  'w.bossDown.4': 'TWINS DOWN!',
  'boss.0': 'ROCK TITAN',
  'boss.0.d': 'Deflect meteors into it',
  'boss.1': 'COMET QUEEN',
  'boss.1.d': 'Glides fast and rains comets',
  'boss.2': 'FROST CITADEL',
  'boss.2.d': 'Break the orbiting crystals first',
  'boss.3': 'SINGULARITY',
  'boss.3.d': 'When the ring closes, your lines shatter!',
  'boss.4': 'TWIN STARS',
  'boss.4.d': 'Down both; the survivor gets angry',

  'hud.skillReady': 'READY',
  'skill.nova': 'STARBURST',
  'skill.nova.d': 'A shockwave rises from the city, wiping every meteor on screen and hitting the boss hard.',
  'skill.warp': 'TIME FRACTURE',
  'skill.warp.d': 'Meteors nearly freeze for 5 seconds and your ink refills 2.5x faster.',
  'skill.aegis': 'AEGIS SHIELD',
  'skill.aegis.d': 'A dome over the city for 7 seconds: meteors that hit it turn to ink and fly back.',
  'skill.starfall': 'STARFALL',
  'skill.starfall.d': '12 homing stars launch from the city and hunt enemies and the boss.',
  'skills.title': 'Skills',
  'skills.desc': 'Destroying meteors fills the skill ring. When full, tap the button at the bottom right. You can equip one skill.',
  'skills.on': 'Equipped',
  'skills.equip': 'Equip',

  'upg.leech.d': '80% more ink from destroyed meteors.',
  'upg.midas.d': '+40% score and gold.',
  'upg.lucky': 'Lucky Star',
  'upg.lucky.d': 'Golden meteors come more often and give +3 gold.',
  'upg.ink_surge': 'Ink Surge',
  'upg.ink_surge.d': '+{v} ink every 10 combo.',
  'upg.magnet': 'Magnet Nib',
  'upg.magnet.d': 'Deflected meteors curve toward the nearest enemy.',
  'upg.frost': 'Hoarfrost',
  'upg.frost.d': 'Every deflect slows nearby enemies for {v}s.',
  'upg.ricochet': 'Ricochet',
  'upg.ricochet.d': 'Deflected meteors bounce off the sky {v} time(s).',
  'upg.overcharge': 'Overcharge',
  'upg.overcharge.d': 'The skill ring fills {v}% faster.',
  'upg.second_wind': 'Second Wind',
  'upg.second_wind.d': 'When a district falls, your ink refills and time slows for a moment.',
  'upg.guardian': 'Guardian Satellite',
  'upg.guardian.d': 'A satellite circling the city lasers the lowest meteor every {v}s.',

  'revive.video': 'WATCH VIDEO · CONTINUE',
  'revive.free': 'CONTINUE · AD-FREE',

  'over.double': 'Watch a video to double your gold (+{n})',
  'gift.claim2x': 'CLAIM 2X · {n}',

  'ad.tag': 'AD',
  'ad.title': 'Rewarded video',
  'ad.desc': 'In the app a short video plays here. This preview shows a placeholder.',
  'ad.close': 'Claim reward',

  'shop.title': 'Shop',
  'shop.coins': 'Gold packs',
  'shop.popular': 'MOST POPULAR',
  'shop.best': 'BEST VALUE',
  'shop.once': 'ONE TIME',
  'shop.starter': 'Starter Pack',
  'shop.starterDesc': '{n} gold + the Time Fracture skill. For new players.',
  'shop.noads': 'No Ads',
  'shop.noadsDesc': 'Every reward instantly, no videos: continues, 2x gold, gifts.',
  'shop.noadsOwned': 'Active. Rewards arrive instantly, no videos.',
  'shop.free': 'Free {n} gold',
  'shop.freeLeft': '{n}/{max} left today',
  'shop.watch': 'Watch',
  'shop.restore': 'Restore purchases',
  'shop.demo': 'Preview: no real payment, packs are added instantly for testing.',

  'toast.noAds': 'No Ads: instant reward!',
  'toast.adFail': 'No video right now, try again soon',
  'toast.adSkip': 'Watch the whole video for the reward',
  'toast.storeOff': 'The store is unavailable right now',
  'toast.buyFail': 'Purchase could not be completed',
  'toast.demoBuy': 'Preview: no payment taken',
  'toast.noAdsOn': 'No Ads active. Thank you!',
  'toast.bought': '+{n} gold',
  'toast.restored': 'Purchases restored',
  'toast.nothing': 'Nothing to restore',
  'toast.needCoins': 'Not enough gold',
});
