import { extend } from '../i18n';

// Sürüm 1.2: uzay dünyaları, yeni meteorlar, bosslar, yetenekler, mağaza ve ödüllü videolar

extend('tr', {
  'w.combo.200': 'ŞEHİR SENİNLE!',
  'menu.shop': 'Mağaza',
  'menu.skills': 'Yetenek',

  'atm.orion': 'Orion Bulutsusu',
  'atm.orion.d': 'Avcı takımyıldızının kuşağı altında renkli bir yıldız doğumevi.',
  'atm.saturn': 'Satürn Halkaları',
  'atm.saturn.d': 'Dev halkaların gölgesinde buz kristalleri yağar.',
  'atm.horizon': 'Olay Ufku',
  'atm.horizon.d': 'Işığı bile yutan kara delik; hayaletler çoğalır.',
  'atm.nova': 'Süpernova',
  'atm.nova.d': 'Patlayan bir yıldızın ışığında son ve sonsuz dünya.',

  // meteorlar ve bosslar
  'w.frozen': 'DONDU!',
  'w.shieldBreak': 'KRİSTAL KIRILDI',
  'w.shielded': 'KALKAN!',
  'w.twinDown': 'BİR İKİZ DÜŞTÜ!',
  'w.secondWind': 'İKİNCİ NEFES!',
  'w.bossDown.0': 'KAYA TİTANI DÜŞTÜ!',
  'w.bossDown.1': 'KRALİÇE DÜŞTÜ!',
  'w.bossDown.2': 'KALE YIKILDI!',
  'w.bossDown.3': 'TEKİLLİK SÖNDÜ!',
  'w.bossDown.4': 'İKİZLER DÜŞTÜ!',
  'boss.0': 'KAYA TİTANI',
  'boss.0.d': 'Sektirdiğin meteorları ona çarptır',
  'boss.1': 'KUYRUKLU KRALİÇE',
  'boss.1.d': 'Hızlı süzülür, kuyruklu yıldız yağdırır',
  'boss.2': 'BUZ KALESİ',
  'boss.2.d': 'Önce dönen kristalleri kır',
  'boss.3': 'TEKİLLİK',
  'boss.3.d': 'Halka daralınca çizgilerin kırılır!',
  'boss.4': 'İKİZ YILDIZLAR',
  'boss.4.d': 'İkisini de düşür, biri kalırsa öfkelenir',

  // yetenekler
  'skill.nova': 'YILDIZ PATLAMASI',
  'skill.warp': 'ZAMAN KIRILMASI',
  'skill.aegis': 'AEGIS KALKANI',
  'skill.starfall': 'YILDIZ YAĞMURU',
  'skills.on': 'Takılı',
  'skills.equip': 'Tak',

  // kartlar
  'upg.leech.d': 'Patlattığın meteorlardan %80 fazla mürekkep.',
  'upg.midas.d': 'Puan ve altın kazancı +%40.',
  'upg.lucky': 'Şans Yıldızı',
  'upg.lucky.d': 'Altın meteorlar daha sık gelir ve +3 altın verir.',
  'upg.ink_surge': 'Mürekkep Dalgası',
  'upg.ink_surge.d': 'Her 10 komboda +{v} mürekkep.',
  'upg.magnet': 'Mıknatıs Uç',
  'upg.magnet.d': 'Sektirdiğin meteorlar en yakın düşmana doğru kıvrılır.',
  'upg.frost': 'Kırağı',
  'upg.frost.d': 'Her sekme çevresindeki düşmanları {v} sn yavaşlatır.',
  'upg.ricochet': 'Sekme Ustası',
  'upg.ricochet.d': 'Sektirdiğin meteorlar tavandan {v} kez geri döner.',
  'upg.overcharge': 'Aşırı Yük',
  'upg.second_wind': 'İkinci Nefes',
  'upg.second_wind.d': 'Bir mahalle yıkılınca mürekkep dolar, zaman bir an yavaşlar.',
  'upg.guardian': 'Koruyucu Uydu',
  'upg.guardian.d': 'Şehrin üstünde dönen uydu her {v} sn\'de en alçak meteoru lazerle vurur.',

  // devam
  'revive.desc': 'Üç mahalleyi yeniden kur, kaldığın yerden devam et.',
  'revive.video': 'VİDEO İZLE · DEVAM ET',
  'revive.free': 'DEVAM ET · REKLAMSIZ',

  // oyun sonu / hediye
  'over.double': 'Video izle, altınları ikiye katla (+{n})',
  'gift.claim2x': '2 KAT AL · {n}',

  // demo reklam
  'ad.tag': 'REKLAM',
  'ad.title': 'Ödüllü video',
  'ad.desc': 'Uygulamada burada kısa bir video oynar. Bu önizlemede temsili gösterilir.',
  'ad.close': 'Ödülü al',

  // mağaza
  'shop.title': 'Mağaza',
  'shop.coins': 'Altın paketleri',
  'shop.popular': 'EN POPÜLER',
  'shop.best': 'EN İYİ DEĞER',
  'shop.once': 'TEK SEFER',
  'shop.starter': 'Başlangıç Paketi',
  'shop.starterDesc': '{n} altın + Zaman Kırılması yeteneği. Yeni oyunculara özel.',
  'shop.noads': 'Reklamsız',
  'shop.free': 'Ücretsiz {n} altın',
  'shop.freeLeft': 'Bugün {n}/{max} hak kaldı',
  'shop.watch': 'İzle',
  'shop.restore': 'Satın alımları geri yükle',
  'shop.demo': 'Önizleme: gerçek ödeme alınmaz, paketler denemek için anında eklenir.',

  // bildirimler
  'toast.noAds': 'Reklamsız: ödül anında!',
  'toast.adLoading': 'Video hazırlanıyor…',
  'toast.adFail': 'Şu an video yok, biraz sonra dene',
  'toast.adSkip': 'Ödül için videoyu sonuna kadar izle',
  'toast.storeOff': 'Mağaza şu an kullanılamıyor',
  'toast.buyFail': 'Satın alma tamamlanamadı',
  'toast.demoBuy': 'Önizleme: ödeme alınmadı',
  'toast.noAdsOn': 'Reklamsız etkin. Teşekkürler!',
  'toast.bought': '+{n} altın',
  'toast.restored': 'Satın alımlar geri yüklendi',
  'toast.nothing': 'Geri yüklenecek satın alım yok',
  'toast.needCoins': 'Yeterli altın yok',
  // 1.7: Orion takımyıldızı, yeni yetenekler, parşömenler
  'worlds.ask': 'Hangi dünyadan devam etmek istersin?',
  'worlds.sub': 'Seçtiğin dünyada oyun hemen başlar. Güç kartlarını dalgaları geçtikçe tek tek kazanırsın; atölye geliştirmelerin her dünyada seninle.',
  'worlds.open': '{a}/{b} dünya açık',
  'worlds.go': 'Buradan Başla',
  'worlds.continue': 'Devam Et',
  'worlds.lockedAt': '{n}. dalgada açılır',
  'skills.title': 'Yetenek Takımyıldızı',
  'skills.desc': 'Her yıldız bir yetenek. Bir yıldıza dokun, şeklini öğren: oyunda o şekli çizince yetenek atılır.',
  'skills.scrolls': 'Yetenek Parşömenleri',
  'skills.scrollNote': 'Yetenek parşömeni oyun içinde sadece 3 tane kullanılabilir. Parşömenler oyunda alt kısımda görünür ve yeteneğin nasıl aktif edileceğini gösterir. Tüm yetenekler oyun içinde kullanılabilir; sadece 3 yeteneği rehber olarak parşömen kutucuğuna koyabilirsin.',
  'skills.addScroll': 'Parşömene koy',
  'skills.removeScroll': 'Parşömenden çıkar',
  'skills.inScroll': 'Parşömende',
  'skills.empty': 'Boş',
  'skills.how': 'Oyunda ekrana {shape} çiz: {name} atılır. Bekleme süresi dolunca istediğin kadar kullan.',
  'toast.scrollFull': 'Parşömenler dolu: önce birini çıkar',
  'shape.spiral': 'Sarmal',
  'shape.star': 'Yıldız',
  'shape.infinity': 'Sonsuzluk',
  'skill.nova.short': 'Patlama',
  'skill.warp.short': 'Zaman',
  'skill.aegis.short': 'Kalkan',
  'skill.starfall.short': 'Yağmur',
  'skill.vortex.short': 'Girdap',
  'skill.beams.short': 'Işınlar',
  'skill.echo.short': 'Yansıma',
  'skill.vortex': 'KARA GİRDAP',
  'skill.vortex.d': 'Çizdiğin sarmalın merkezinde bir girdap açılır: yakındaki meteorları içine çekip yutar, boss\'u saniyede bir yıpratır.',
  'skill.vortex.p': '{v} sn girdap',
  'skill.beams': 'YILDIZ IŞINLARI',
  'skill.beams.d': 'Çizdiğin yıldızın merkezinden beş yöne ekranı kesen ışınlar: yoldaki bütün meteorlar yok olur.',
  'skill.beams.p': 'Boss hasarı {v}',
  'skill.echo': 'SONSUZ YANSIMA',
  'skill.echo.d': 'Bir süre her sektirdiğin meteor iki yansımayla üçe bölünür; çizgilerin gökkuşağına döner.',
  'skill.echo.p': '{v} sn yansıma',
  // 1.5: seçilen dünyadan başlama, geçiş reklamı
  'up.subChapter': '{w} için hazırlan · {i}/{n}',
  'worlds.desc': 'Her beş dalgada yeni bir dünya açılır. Açtığın bir dünyayı seçersen oyuna doğrudan o dünyadan başlarsın; güç kartlarını dalgaları geçtikçe kazanırsın.',
  'ad.titleInter': 'Reklam',
  'ad.descInter': 'Uygulamada burada kısa bir reklam gösterilir. Reklamsız paketle hiç çıkmaz.',
  'ad.continue': 'Devam et',
  'shop.noadsDesc': 'Araya giren reklamlar kalkar, tüm video ödülleri anında: devam, 2 kat altın, hediyeler.',
  'shop.noadsOwned': 'Etkin. Reklam yok, ödüller video izlemeden anında gelir.',
  // 1.4: stratejik çizgi, yeni meteorlar, Mürekkep Ateşi
  'w.tooHigh': 'ÇOK YÜKSEK!',
  'w.heat': 'Üst atmosferde mürekkep çabuk yanar',
  'w.burn': 'YANDI!',
  'w.prism': 'PRİZMA!',
  'w.mend': 'ŞİFA!',
  'w.bank': 'BİLARDO! +{n}',
  'w.fever': 'MÜREKKEP ATEŞİ!',
  'w.feverSub': 'Mürekkep bedava, puan x1,5',
  'mk.blink': 'IŞINLANAN METEOR',
  'mk.blink.d': 'Parlayınca yana ışınlanır!',
  'mk.flare': 'ALEV METEORU',
  'mk.flare.d': 'Sektiği çizgiyi yakar!',
  'mk.prism': 'PRİZMA',
  'mk.prism.d': 'Sektir, üçe bölünsün!',
  'mk.mender': 'ŞİFA KRİSTALİ',
  'mk.mender.d': 'Sektir, şehri onarsın!',
  'mk.wisp': 'KIVILCIM SÜRÜSÜ',
  'mk.wisp.d': 'Dalgalanarak iner',
  'hud.fever': 'ATEŞ',
  // 1.3: şekil çizerek yetenek
  'hud.skillReady': 'ÇİZ',
  'shape.circle': 'Daire',
  'shape.triangle': 'Üçgen',
  'shape.square': 'Kare',
  'shape.zigzag': 'Zikzak',
  'skill.readyHint': '{name} hazır! Ekrana {shape} çiz',
  'skill.nova.d': 'Çizdiğin dairenin merkezinden yayılan şok dalgası ekrandaki meteorları yok eder, boss\'a ağır hasar verir.',
  'skill.warp.d': 'Düşman meteorlar neredeyse durur, mürekkebin hızlı dolar.',
  'skill.aegis.d': 'Şehrin üstünde bir kubbe: çarpan meteorlar mürekkebe dönüp geri fırlar.',
  'skill.starfall.d': 'Şehirden güdümlü yıldızlar fırlar, düşmanları ve boss\'u avlar.',
  'skill.nova.p': 'Boss hasarı {v}',
  'skill.warp.p': '{v} sn zaman kırılması',
  'skill.aegis.p': '{v} sn kalkan',
  'skill.starfall.p': '{v} güdümlü yıldız',
  'skills.draw': 'Çiz',
  'skills.cd': '{n} sn bekleme',
  'skills.lv': 'Sv {n}',
  'skills.max': 'EN ÜST SEVİYE',
  'skills.upgrade': 'Geliştir',
  'skills.unlock': 'Aç',
  'skills.next': 'Sonraki',
  'upg.overcharge.d': 'Yetenek bekleme süreleri %{v} daha hızlı dolar.',
  'toast.skillUp': '{name} seviye {n}!',
  'toast.skillNew': '{name} açıldı! Oyunda {shape} çiz',
});

extend('en', {
  'w.combo.200': 'THE CITY IS WITH YOU!',
  'menu.shop': 'Shop',
  'menu.skills': 'Skill',

  'atm.orion': 'Orion Nebula',
  'atm.orion.d': "A colourful stellar nursery under the Hunter's belt.",
  'atm.saturn': "Saturn's Rings",
  'atm.saturn.d': 'Ice crystals fall in the shadow of the giant rings.',
  'atm.horizon': 'Event Horizon',
  'atm.horizon.d': 'A black hole that swallows even light; phantoms multiply.',
  'atm.nova': 'Supernova',
  'atm.nova.d': 'The last, endless world, lit by an exploding star.',

  'w.frozen': 'FROZEN!',
  'w.shieldBreak': 'CRYSTAL BROKEN',
  'w.shielded': 'SHIELDED!',
  'w.twinDown': 'ONE TWIN DOWN!',
  'w.secondWind': 'SECOND WIND!',
  'w.bossDown.0': 'ROCK TITAN DOWN!',
  'w.bossDown.1': 'QUEEN DOWN!',
  'w.bossDown.2': 'CITADEL SHATTERED!',
  'w.bossDown.3': 'SINGULARITY COLLAPSED!',
  'w.bossDown.4': 'TWINS DOWN!',
  'boss.0': 'ROCK TITAN',
  'boss.0.d': 'Deflect meteors into it',
  'boss.1': 'COMET QUEEN',
  'boss.1.d': 'Glides fast and rains comets',
  'boss.2': 'FROST CITADEL',
  'boss.2.d': 'Break the orbiting crystals first',
  'boss.3': 'SINGULARITY',
  'boss.3.d': 'When the ring closes, your lines shatter!',
  'boss.4': 'TWIN STARS',
  'boss.4.d': 'Down both; the survivor gets angry',

  'skill.nova': 'STARBURST',
  'skill.warp': 'TIME FRACTURE',
  'skill.aegis': 'AEGIS SHIELD',
  'skill.starfall': 'STARFALL',
  'skills.on': 'Equipped',
  'skills.equip': 'Equip',

  'upg.leech.d': '80% more ink from destroyed meteors.',
  'upg.midas.d': '+40% score and gold.',
  'upg.lucky': 'Lucky Star',
  'upg.lucky.d': 'Golden meteors come more often and give +3 gold.',
  'upg.ink_surge': 'Ink Surge',
  'upg.ink_surge.d': '+{v} ink every 10 combo.',
  'upg.magnet': 'Magnet Nib',
  'upg.magnet.d': 'Deflected meteors curve toward the nearest enemy.',
  'upg.frost': 'Hoarfrost',
  'upg.frost.d': 'Every deflect slows nearby enemies for {v}s.',
  'upg.ricochet': 'Ricochet',
  'upg.ricochet.d': 'Deflected meteors bounce off the sky {v} time(s).',
  'upg.overcharge': 'Overcharge',
  'upg.second_wind': 'Second Wind',
  'upg.second_wind.d': 'When a district falls, your ink refills and time slows for a moment.',
  'upg.guardian': 'Guardian Satellite',
  'upg.guardian.d': 'A satellite circling the city lasers the lowest meteor every {v}s.',

  'revive.video': 'WATCH VIDEO · CONTINUE',
  'revive.free': 'CONTINUE · AD-FREE',

  'over.double': 'Watch a video to double your gold (+{n})',
  'gift.claim2x': 'CLAIM 2X · {n}',

  'ad.tag': 'AD',
  'ad.title': 'Rewarded video',
  'ad.desc': 'In the app a short video plays here. This preview shows a placeholder.',
  'ad.close': 'Claim reward',

  'shop.title': 'Shop',
  'shop.coins': 'Gold packs',
  'shop.popular': 'MOST POPULAR',
  'shop.best': 'BEST VALUE',
  'shop.once': 'ONE TIME',
  'shop.starter': 'Starter Pack',
  'shop.starterDesc': '{n} gold + the Time Fracture skill. For new players.',
  'shop.noads': 'No Ads',
  'shop.free': 'Free {n} gold',
  'shop.freeLeft': '{n}/{max} left today',
  'shop.watch': 'Watch',
  'shop.restore': 'Restore purchases',
  'shop.demo': 'Preview: no real payment, packs are added instantly for testing.',

  'toast.noAds': 'No Ads: instant reward!',
  'toast.adLoading': 'Preparing video…',
  'toast.adFail': 'No video right now, try again soon',
  'toast.adSkip': 'Watch the whole video for the reward',
  'toast.storeOff': 'The store is unavailable right now',
  'toast.buyFail': 'Purchase could not be completed',
  'toast.demoBuy': 'Preview: no payment taken',
  'toast.noAdsOn': 'No Ads active. Thank you!',
  'toast.bought': '+{n} gold',
  'toast.restored': 'Purchases restored',
  'toast.nothing': 'Nothing to restore',
  'toast.needCoins': 'Not enough gold',
  // 1.7: Orion constellation, new skills, scrolls
  'worlds.ask': 'Which world do you want to continue from?',
  'worlds.sub': 'Your run starts right in the world you pick. Power cards are earned one by one as you clear waves; your workshop upgrades come with you everywhere.',
  'worlds.open': '{a}/{b} worlds open',
  'worlds.go': 'Start Here',
  'worlds.continue': 'Continue',
  'worlds.lockedAt': 'Unlocks at wave {n}',
  'skills.title': 'Skill Constellation',
  'skills.desc': 'Every star is a skill. Tap a star to learn its shape: draw that shape in game to cast it.',
  'skills.scrolls': 'Skill Scrolls',
  'skills.scrollNote': 'Only 3 skill scrolls can be used in game. Scrolls appear at the bottom of the screen and show how to activate the skill. Every skill can be used in game; you can only place 3 skills in the scroll slots as guides.',
  'skills.addScroll': 'Add to scrolls',
  'skills.removeScroll': 'Remove scroll',
  'skills.inScroll': 'In scrolls',
  'skills.empty': 'Empty',
  'skills.how': 'Draw a {shape} on screen in game to cast {name}. Use it as often as you like once the cooldown ends.',
  'toast.scrollFull': 'Scrolls are full: remove one first',
  'shape.spiral': 'Spiral',
  'shape.star': 'Star',
  'shape.infinity': 'Infinity',
  'skill.nova.short': 'Burst',
  'skill.warp.short': 'Time',
  'skill.aegis.short': 'Shield',
  'skill.starfall.short': 'Starfall',
  'skill.vortex.short': 'Vortex',
  'skill.beams.short': 'Beams',
  'skill.echo.short': 'Echo',
  'skill.vortex': 'DARK VORTEX',
  'skill.vortex.d': 'A vortex opens at the centre of your spiral: it pulls in and swallows nearby meteors and wears the boss down every second.',
  'skill.vortex.p': '{v}s vortex',
  'skill.beams': 'STAR BEAMS',
  'skill.beams.d': 'Five beams burst from the centre of your star and cut across the screen, wiping every meteor in their path.',
  'skill.beams.p': 'Boss damage {v}',
  'skill.echo': 'INFINITE ECHO',
  'skill.echo.d': 'For a while every meteor you deflect splits into three with two echoes; your lines turn rainbow.',
  'skill.echo.p': '{v}s echo',
  // 1.5: start from the selected world, interstitial ads
  'up.subChapter': 'Get ready for {w} · {i}/{n}',
  'worlds.desc': 'A new world opens every five waves. Select an unlocked world to start your run right there; power cards are earned as you clear waves.',
  'ad.titleInter': 'Advertisement',
  'ad.descInter': 'In the app a short ad plays here. The No Ads pack removes it for good.',
  'ad.continue': 'Continue',
  'shop.noadsDesc': 'Removes interstitial ads and gives every video reward instantly: continues, 2x gold, gifts.',
  'shop.noadsOwned': 'Active. No ads, rewards arrive instantly.',
  // 1.4: strategic lines, new meteors, Ink Fever
  'w.tooHigh': 'TOO HIGH!',
  'w.heat': 'Ink burns fast in the upper atmosphere',
  'w.burn': 'BURNED!',
  'w.prism': 'PRISM!',
  'w.mend': 'HEALED!',
  'w.bank': 'BANK SHOT! +{n}',
  'w.fever': 'INK FEVER!',
  'w.feverSub': 'Free ink, score x1.5',
  'mk.blink': 'BLINK METEOR',
  'mk.blink.d': 'Teleports sideways when it glows!',
  'mk.flare': 'FLARE METEOR',
  'mk.flare.d': 'Burns the line it bounces off!',
  'mk.prism': 'PRISM',
  'mk.prism.d': 'Deflect it to split in three!',
  'mk.mender': 'MENDING CRYSTAL',
  'mk.mender.d': 'Deflect it to repair the city!',
  'mk.wisp': 'WISP SWARM',
  'mk.wisp.d': 'Weaves as it falls',
  'hud.fever': 'FEVER',
  // 1.3: draw a shape to cast
  'hud.skillReady': 'DRAW',
  'shape.circle': 'Circle',
  'shape.triangle': 'Triangle',
  'shape.square': 'Square',
  'shape.zigzag': 'Zigzag',
  'skill.readyHint': '{name} is ready! Draw a {shape}',
  'skill.nova.d': 'A shockwave bursts from the centre of your circle, wiping meteors on screen and hitting the boss hard.',
  'skill.warp.d': 'Enemy meteors nearly freeze and your ink refills fast.',
  'skill.aegis.d': 'A dome over the city: meteors that hit it turn to ink and fly back.',
  'skill.starfall.d': 'Homing stars launch from the city and hunt enemies and the boss.',
  'skill.nova.p': 'Boss damage {v}',
  'skill.warp.p': '{v}s time fracture',
  'skill.aegis.p': '{v}s shield',
  'skill.starfall.p': '{v} homing stars',
  'skills.draw': 'Draw',
  'skills.cd': '{n}s cooldown',
  'skills.lv': 'Lv {n}',
  'skills.max': 'MAX LEVEL',
  'skills.upgrade': 'Upgrade',
  'skills.unlock': 'Unlock',
  'skills.next': 'Next',
  'upg.overcharge.d': 'Skill cooldowns recover {v}% faster.',
  'toast.skillUp': '{name} level {n}!',
  'toast.skillNew': '{name} unlocked! Draw a {shape} in game',
});
