import { extend } from '../i18n';

extend('tr', {
  'app.title1': 'MÜREKKEP',
  'app.title2': 'KALKANI',
  'app.tagline': 'Çiz. Sektir. İstanbul’u koru.',
  'app.tap': 'Başlamak için dokun',

  'menu.play': 'OYNA',
  'menu.daily': 'Günlük',
  'menu.missions': 'Görevler',
  'menu.workshop': 'Atölye',
  'menu.pens': 'Kalemler',
  'menu.records': 'Rekorlar',
  'menu.settings': 'Ayarlar',
  'menu.best': 'EN İYİ',
  'menu.toNext': '{rank} için {n} puan',
  'menu.maxRank': 'Zirvedesin',
  'menu.streak': '{n} gün',
  'menu.newMissions': '{n} görev',

  'menu.gift': 'Hediye',
  'menu.worlds': 'Dünyalar',
  'menu.home': 'Ana Sayfa',
  'menu.bestWave': 'En iyi dalga {n}',
  'menu.streakDays': '{n} günlük seri',

  'atm.gece': 'Gece',
  'atm.gece.d': 'Hilalin altında sessiz bir gece.',
  'atm.alaca': 'Alacakaranlık',
  'atm.alaca.d': 'Rüzgâr meteorları sürükler, lale yaprakları uçuşur.',
  'atm.aurora': 'Kuzey Işıkları',
  'atm.aurora.d': 'Kar yağarken buz meteorları çoğalır.',
  'atm.kizil': 'Kızıl Kıyamet',
  'atm.kizil.d': 'Kan ayı doğar; zırhlı ve bölünen meteorlar artar.',
  'atm.kozmos': 'Kozmos',
  'atm.kozmos.d': 'Halkalı gezegenin altında ağır meteorlar.',
  'atm.ebru': 'Ebru Rüyası',
  'atm.ebru.d': 'Bütün renklerin karıştığı son dünya.',

  'worlds.title': 'Dünyalar',
  'worlds.desc': 'Her beş dalgada sahne döner ve yeni bir dünya açılır. Açtığın dünyayı menü arka planı yapabilirsin.',
  'worlds.waves': 'Dalga {a}–{b}',
  'worlds.wavesEnd': 'Dalga {a} ve sonrası',
  'worlds.locked': 'Dalga {n}',
  'worlds.selected': 'Seçili',
  'worlds.select': 'Seç',

  'banner.chapter': 'BÖLÜM {n}',
  'banner.newWorld': 'Yeni dünya!',

  'gift.title': 'Günlük Hediye',
  'gift.desc': 'Her gün uğra, ödül büyüsün. 7. gün büyük hediye!',
  'gift.day': 'Gün {n}',
  'gift.claim': '{n} ALTIN AL',
  'gift.tomorrow': 'Yarın yine gel',
  'gift.got': '+{n} altın',

  'revive.title': 'Şehir düşüyor!',
  'revive.desc': 'Üç mahalleyi yeniden kur, kaldığın yerden devam et.',
  'revive.go': 'DEVAM ET',
  'revive.no': 'Vazgeç',
  'revive.bank': 'Kasandaki altın: {n}',

  'rank.cirak': 'Çırak',
  'rank.kalfa': 'Kalfa',
  'rank.usta': 'Usta',
  'rank.hattat': 'Hattat',
  'rank.ustad': 'Üstad',
  'rank.efsane': 'Efsane',

  'hud.best': 'REKOR',
  'hud.wave': 'DALGA',
  'hud.combo': 'KOMBO',
  'hud.boss': 'KIZIL DEV',
  'hud.newBest': 'YENİ REKOR',

  'banner.wave': 'DALGA {n}',
  'banner.boss': 'KIZIL DEV',
  'banner.bossSub': 'Sektirdiğin meteorları ona çarptır',
  'banner.ready': 'Hazır ol',
  'banner.clear': 'DALGA {n} TEMİZ',
  'banner.bonus': 'Dalga bonusu +{n}',
  'banner.perfect': 'Kusursuz: şehir hiç hasar almadı',

  'up.title': 'Bir güç seç',
  'up.sub': 'Dalga {n} için hazırlan',
  'up.subStart': 'Hattat başlangıcı: bir güçle başla',
  'up.reroll': 'Yenile · {n}',
  'up.level': 'Sv. {n}',
  'up.new': 'YENİ',
  'rarity.0': 'Yaygın',
  'rarity.1': 'Nadir',
  'rarity.2': 'Destansı',
  'rarity.3': 'Efsanevi',

  'upg.ink_regen': 'Hızlı Dolum',
  'upg.ink_regen.d': 'Mürekkep %{v} daha hızlı dolar.',
  'upg.ink_max': 'Geniş Hokka',
  'upg.ink_max.d': 'Mürekkep kapasitesi +{v}.',
  'upg.line_life': 'Kalıcı Mürekkep',
  'upg.line_life.d': 'Çizgiler %{v} daha uzun kalır.',
  'upg.bounce': 'Lastik Uç',
  'upg.bounce.d': 'Sekmeler hızlanır, sekme puanı +%50.',
  'upg.blast': 'Geniş Patlama',
  'upg.blast.d': 'Patlama alanı %{v} büyür, zincirler kolaylaşır.',
  'upg.repair': 'Onarım',
  'upg.repair.d': 'Yıkılan ya da hasarlı bir mahalleyi yeniden inşa et.',
  'upg.extra_line': 'İkinci El',
  'upg.extra_line.d': 'Aynı anda bir çizgi daha çizebilirsin.',
  'upg.leech': 'Mürekkep Sülüğü',
  'upg.leech.d': 'Patlattığın meteorlardan 2 kat mürekkep.',
  'upg.timewarp': 'Zaman Bükücü',
  'upg.timewarp.d': 'Çizerken zaman daha çok yavaşlar, çizim %15 ucuzlar.',
  'upg.thick': 'Kalın Uç',
  'upg.thick.d': 'Çizgiler kalınlaşır, zırhlı meteorlar kıramaz.',
  'upg.comet': 'Patlayan Kuyruk',
  'upg.comet.d': 'Göğe kaçan meteorların patlar, yukarıdan gelenleri vurur.',
  'upg.dome': 'Kubbe',
  'upg.dome.d': 'Her dalga şehri bir kez daha koruyan kalkan.',
  'upg.mirror': 'Ayna',
  'upg.mirror.d': 'Sektirdiğin meteor bölünür, ek parçalar da senin.',
  'upg.chain': 'Zincir Şimşek',
  'upg.chain.d': 'Her patlama {v} yakın meteora şimşek çaktırır.',
  'upg.fire': 'Ateş Mürekkebi',
  'upg.fire.d': 'Çizgine değen meteor %{v} ihtimalle anında yanar.',
  'upg.pierce': 'Delici',
  'upg.pierce.d': 'Sektirdiğin meteor {v} meteoru delip geçer.',
  'upg.blackhole': 'Kara Delik',
  'upg.blackhole.d': 'Her 15 komboda meteorları yutan bir kara delik açılır.',
  'upg.midas': 'Altın Dokunuş',
  'upg.midas.d': 'Puan ve altın kazancı +%50.',
  'upg.phoenix': 'Anka Kuşu',
  'upg.phoenix.d': 'Şehir düştüğünde bir kez küllerinden doğar.',

  'pause.title': 'Duraklatıldı',
  'pause.resume': 'DEVAM',
  'pause.restart': 'Yeniden başla',
  'pause.menu': 'Ana menü',
  'pause.note': 'Menüye dönersen bu oyunun puanı kaydedilir.',

  'over.title': 'ŞEHİR DÜŞTÜ',
  'over.score': 'PUAN',
  'over.newBest': 'YENİ REKOR!',
  'over.toBest': 'Rekoruna {n} puan kaldı',
  'over.wave': 'Dalga',
  'over.combo': 'En iyi kombo',
  'over.kills': 'Patlatılan',
  'over.time': 'Süre',
  'over.coins': 'Kazanılan altın',
  'over.again': 'TEKRAR',
  'over.menu': 'Menü',
  'over.rankUp': 'Rütbe atladın',
  'over.dailyBest': 'Bugünün yeni en iyisi!',
  'over.daily': 'Günlük en iyin: {n}',
  'over.streak': '{n} günlük seri bonusu',
  'over.mission': 'Görev tamamlandı',

  'daily.title': 'Günlük Meydan Okuma',
  'daily.desc': 'Bugün herkes aynı meteor dizisiyle oynuyor. Günün kuralı:',
  'daily.best': 'Bugünkü en iyin',
  'daily.attempts': '{n} deneme',
  'daily.play': 'BUGÜNÜ OYNA',
  'daily.coins': 'Altın ödülü x1,5',
  'daily.resets': 'Yenilenmesine {h} sa {m} dk',
  'daily.streak': 'Seri',
  'daily.streakDays': '{n} gün',
  'daily.streakHint': 'Her gün oyna, seri bonusu büyüsün (7 güne kadar).',

  'mod.storm': 'Fırtına',
  'mod.storm.d': 'Meteorlar %28 daha hızlı. Puan x1,5.',
  'mod.goldrush': 'Altın Yağmuru',
  'mod.goldrush.d': 'Altın meteorlar dört kat sık.',
  'mod.shortink': 'Uçucu Mürekkep',
  'mod.shortink.d': 'Çizgiler yarı ömürlü. Puan x1,3.',
  'mod.giants': 'Devler',
  'mod.giants.d': 'Meteorlar iri ama yavaş.',
  'mod.chaos': 'Kaos',
  'mod.chaos.d': 'Tüm meteor türleri ilk dalgadan itibaren. Puan x1,25.',
  'mod.mirrorday': 'Ayna Günü',
  'mod.mirrorday.d': 'Oyuna Ayna gücüyle başla.',
  'mod.oneline': 'Tek Çizgi',
  'mod.oneline.d': 'Aynı anda yalnızca bir çizgi. Puan x1,6.',

  'missions.title': 'Görevler',
  'missions.desc': 'Tamamladığın görev altın kazandırır, yerine yenisi gelir.',
  'm.kills': 'Tek oyunda {n} meteor patlat',
  'm.combo': 'Tek oyunda {n}x kombo yap',
  'm.wave': '{n}. dalgaya ulaş',
  'm.score': 'Tek oyunda {n} puan topla',
  'm.perfect': 'Tek oyunda {n} kusursuz dalga',
  'm.boss': 'Toplam {n} Kızıl Dev yen',
  'm.golden': 'Toplam {n} altın meteor patlat',
  'm.oneline': 'Tek çizgiyle {n} meteor sektir',
  'm.chain': 'Tek zincirde {n} meteor patlat',
  'm.deflects': 'Toplam {n} meteor sektir',
  'm.daily': 'Günlük meydan okumayı {n} kez oyna',

  'workshop.title': 'Atölye',
  'workshop.desc': 'Kalıcı geliştirmeler her oyunda seninle.',
  'workshop.max': 'TAM',
  'ws.ink': 'Derin Hokka',
  'ws.ink.d': 'Mürekkep kapasitesi +12',
  'ws.regen': 'Usta Eli',
  'ws.regen.d': 'Mürekkep dolumu +%8',
  'ws.dome': 'Sağlam Temel',
  'ws.dome.d': 'Oyuna +1 kubbe şarjıyla başla',
  'ws.reroll': 'Şanslı Kalem',
  'ws.reroll.d': 'Güç kartlarını oyun başına +1 kez yenile',
  'ws.coin': 'Kese',
  'ws.coin.d': 'Altın kazancı +%10',
  'ws.golden': 'Altın Radar',
  'ws.golden.d': 'Altın meteorlar daha sık gelir',
  'ws.start': 'Hattat Başlangıcı',
  'ws.start.d': 'Oyuna nadir bir güçle başla (Sv. 2: destansı)',

  'pens.title': 'Kalemler',
  'pens.desc': 'Mürekkebinin rengini seç. Bazıları yalnızca rütbeyle açılır.',
  'pen.turkuaz': 'Turkuaz',
  'pen.lale': 'Lale',
  'pen.safran': 'Safran',
  'pen.zumrut': 'Zümrüt',
  'pen.menekse': 'Menekşe',
  'pen.ates': 'Ateş',
  'pen.buz': 'Buz',
  'pen.gokkusagi': 'Gökkuşağı',
  'pens.equip': 'Kullan',
  'pens.equipped': 'Kullanılıyor',
  'pens.needRank': '{rank} gerekli',

  'records.title': 'Rekorlar',
  'records.empty': 'Henüz rekor yok. İlk oyununu oyna!',
  'records.top': 'En iyi 10 oyun',
  'records.stats': 'İstatistikler',
  'st.runs': 'Oyun',
  'st.kills': 'Patlatılan meteor',
  'st.wave': 'En iyi dalga',
  'st.combo': 'En iyi kombo',
  'st.boss': 'Yenilen Kızıl Dev',
  'st.time': 'Oynama süresi',
  'st.daily': 'günlük',

  'settings.title': 'Ayarlar',
  'settings.music': 'Müzik',
  'settings.sfx': 'Ses efektleri',
  'settings.haptics': 'Titreşim',
  'settings.quality': 'Grafik',
  'q.high': 'Yüksek',
  'q.balanced': 'Dengeli',
  'q.saver': 'Pil dostu',
  'settings.lang': 'Dil',
  'lang.auto': 'Otomatik',
  'settings.fps': 'FPS göstergesi',
  'settings.tutorial': 'Eğitimi tekrar oyna',
  'settings.reset': 'İlerlemeyi sıfırla',
  'settings.resetConfirm': 'Emin misin? Silmek için tekrar dokun',
  'settings.resetDone': 'İlerleme sıfırlandı',
  'settings.fullscreen': 'Tam ekran',
  'settings.credits': 'Mürekkep Kalkanı · sürüm {v}',

  'tut.0': 'Parmağını sürükleyip meteorun altına bir çizgi çiz',
  'tut.1': 'Sektirdiğin meteoru diğerine çarptır: ikisi de patlar',
  'tut.2': 'Mürekkep sınırlı, üstteki bara dikkat et. Hazırsın!',
  'tut.skip': 'Eğitimi atla',

  'common.back': 'Geri',
  'common.close': 'Kapat',
  'common.on': 'Açık',
  'common.off': 'Kapalı',
  'common.min': '{m} dk',
  'common.hm': '{h} sa {m} dk',
  'toast.record': 'Yeni rekor!',
});

extend('en', {
  'app.title1': 'INK',
  'app.title2': 'SHIELD',
  'app.tagline': 'Draw. Deflect. Save Istanbul.',
  'app.tap': 'Tap to start',

  'menu.play': 'PLAY',
  'menu.daily': 'Daily',
  'menu.missions': 'Missions',
  'menu.workshop': 'Workshop',
  'menu.pens': 'Pens',
  'menu.records': 'Records',
  'menu.settings': 'Settings',
  'menu.best': 'BEST',
  'menu.toNext': '{n} points to {rank}',
  'menu.maxRank': 'You are at the top',
  'menu.streak': '{n} days',
  'menu.newMissions': '{n} missions',

  'menu.gift': 'Gift',
  'menu.worlds': 'Worlds',
  'menu.home': 'Home',
  'menu.bestWave': 'Best wave {n}',
  'menu.streakDays': '{n}-day streak',

  'atm.gece': 'Night',
  'atm.gece.d': 'A quiet night under the crescent.',
  'atm.alaca': 'Dusk',
  'atm.alaca.d': 'Wind drags the meteors, tulip petals fly.',
  'atm.aurora': 'Northern Lights',
  'atm.aurora.d': 'Snow falls and ice meteors multiply.',
  'atm.kizil': 'Crimson Doom',
  'atm.kizil.d': 'A blood moon rises; armored and splitting meteors grow.',
  'atm.kozmos': 'Cosmos',
  'atm.kozmos.d': 'Heavy meteors under a ringed planet.',
  'atm.ebru': 'Ebru Dream',
  'atm.ebru.d': 'The final world where every color blends.',

  'worlds.title': 'Worlds',
  'worlds.desc': 'Every five waves the stage turns and a new world opens. Set any unlocked world as your menu backdrop.',
  'worlds.waves': 'Waves {a}–{b}',
  'worlds.wavesEnd': 'Wave {a} and beyond',
  'worlds.locked': 'Wave {n}',
  'worlds.selected': 'Selected',
  'worlds.select': 'Select',

  'banner.chapter': 'CHAPTER {n}',
  'banner.newWorld': 'New world!',

  'gift.title': 'Daily Gift',
  'gift.desc': 'Come back every day and the reward grows. Big gift on day 7!',
  'gift.day': 'Day {n}',
  'gift.claim': 'CLAIM {n} GOLD',
  'gift.tomorrow': 'Come back tomorrow',
  'gift.got': '+{n} gold',

  'revive.title': 'The city is falling!',
  'revive.desc': 'Rebuild three districts and carry on where you left off.',
  'revive.go': 'CONTINUE',
  'revive.no': 'Give up',
  'revive.bank': 'Gold in your purse: {n}',

  'rank.cirak': 'Apprentice',
  'rank.kalfa': 'Journeyman',
  'rank.usta': 'Master',
  'rank.hattat': 'Calligrapher',
  'rank.ustad': 'Grandmaster',
  'rank.efsane': 'Legend',

  'hud.best': 'BEST',
  'hud.wave': 'WAVE',
  'hud.combo': 'COMBO',
  'hud.boss': 'RED GIANT',
  'hud.newBest': 'NEW BEST',

  'banner.wave': 'WAVE {n}',
  'banner.boss': 'RED GIANT',
  'banner.bossSub': 'Deflect meteors into it',
  'banner.ready': 'Get ready',
  'banner.clear': 'WAVE {n} CLEAR',
  'banner.bonus': 'Wave bonus +{n}',
  'banner.perfect': 'Perfect: the city took no damage',

  'up.title': 'Pick a power',
  'up.sub': 'Get ready for wave {n}',
  'up.subStart': 'Calligrapher start: begin with a power',
  'up.reroll': 'Reroll · {n}',
  'up.level': 'Lv. {n}',
  'up.new': 'NEW',
  'rarity.0': 'Common',
  'rarity.1': 'Rare',
  'rarity.2': 'Epic',
  'rarity.3': 'Legendary',

  'upg.ink_regen': 'Quick Refill',
  'upg.ink_regen.d': 'Ink refills {v}% faster.',
  'upg.ink_max': 'Deep Inkwell',
  'upg.ink_max.d': 'Ink capacity +{v}.',
  'upg.line_life': 'Lasting Ink',
  'upg.line_life.d': 'Lines last {v}% longer.',
  'upg.bounce': 'Rubber Nib',
  'upg.bounce.d': 'Faster bounces, +50% deflect points.',
  'upg.blast': 'Wide Blast',
  'upg.blast.d': 'Explosions grow {v}%, chains come easier.',
  'upg.repair': 'Repair',
  'upg.repair.d': 'Rebuild a destroyed or damaged district.',
  'upg.extra_line': 'Second Hand',
  'upg.extra_line.d': 'Draw one more line at a time.',
  'upg.leech': 'Ink Leech',
  'upg.leech.d': 'Double ink from destroyed meteors.',
  'upg.timewarp': 'Time Bender',
  'upg.timewarp.d': 'Time slows more while drawing, lines cost 15% less.',
  'upg.thick': 'Broad Nib',
  'upg.thick.d': 'Thicker lines that armored meteors cannot break.',
  'upg.comet': 'Bursting Tail',
  'upg.comet.d': 'Meteors you send skyward explode and hit incoming ones.',
  'upg.dome': 'Dome',
  'upg.dome.d': 'A shield that saves the city once more each wave.',
  'upg.mirror': 'Mirror',
  'upg.mirror.d': 'Deflected meteors split, the pieces are yours too.',
  'upg.chain': 'Chain Lightning',
  'upg.chain.d': 'Every explosion zaps {v} nearby meteors.',
  'upg.fire': 'Fire Ink',
  'upg.fire.d': 'Meteors touching your line have a {v}% chance to burn instantly.',
  'upg.pierce': 'Piercer',
  'upg.pierce.d': 'Deflected meteors pierce through {v} meteors.',
  'upg.blackhole': 'Black Hole',
  'upg.blackhole.d': 'Every 15 combo opens a black hole that swallows meteors.',
  'upg.midas': 'Midas Touch',
  'upg.midas.d': '+50% score and gold.',
  'upg.phoenix': 'Phoenix',
  'upg.phoenix.d': 'When the city falls, it rises from its ashes once.',

  'pause.title': 'Paused',
  'pause.resume': 'RESUME',
  'pause.restart': 'Restart',
  'pause.menu': 'Main menu',
  'pause.note': 'Leaving to the menu still records this run’s score.',

  'over.title': 'THE CITY FELL',
  'over.score': 'SCORE',
  'over.newBest': 'NEW RECORD!',
  'over.toBest': '{n} points short of your record',
  'over.wave': 'Wave',
  'over.combo': 'Best combo',
  'over.kills': 'Destroyed',
  'over.time': 'Time',
  'over.coins': 'Gold earned',
  'over.again': 'AGAIN',
  'over.menu': 'Menu',
  'over.rankUp': 'Rank up',
  'over.dailyBest': 'New best for today!',
  'over.daily': 'Your daily best: {n}',
  'over.streak': '{n}-day streak bonus',
  'over.mission': 'Mission complete',

  'daily.title': 'Daily Challenge',
  'daily.desc': 'Everyone plays the same meteor sequence today. Today’s rule:',
  'daily.best': 'Your best today',
  'daily.attempts': '{n} attempts',
  'daily.play': 'PLAY TODAY',
  'daily.coins': 'Gold reward x1.5',
  'daily.resets': 'Resets in {h}h {m}m',
  'daily.streak': 'Streak',
  'daily.streakDays': '{n} days',
  'daily.streakHint': 'Play every day to grow your streak bonus (up to 7 days).',

  'mod.storm': 'Storm',
  'mod.storm.d': 'Meteors 28% faster. Score x1.5.',
  'mod.goldrush': 'Gold Rush',
  'mod.goldrush.d': 'Golden meteors four times as often.',
  'mod.shortink': 'Fleeting Ink',
  'mod.shortink.d': 'Lines last half as long. Score x1.3.',
  'mod.giants': 'Giants',
  'mod.giants.d': 'Meteors are huge but slow.',
  'mod.chaos': 'Chaos',
  'mod.chaos.d': 'Every meteor type from wave one. Score x1.25.',
  'mod.mirrorday': 'Mirror Day',
  'mod.mirrorday.d': 'Start with the Mirror power.',
  'mod.oneline': 'One Line',
  'mod.oneline.d': 'Only one line at a time. Score x1.6.',

  'missions.title': 'Missions',
  'missions.desc': 'Finished missions pay gold and a new one takes their place.',
  'm.kills': 'Destroy {n} meteors in one run',
  'm.combo': 'Reach a {n}x combo in one run',
  'm.wave': 'Reach wave {n}',
  'm.score': 'Score {n} in one run',
  'm.perfect': 'Perfect waves in one run: {n}',
  'm.boss': 'Red Giants defeated in total: {n}',
  'm.golden': 'Golden meteors destroyed in total: {n}',
  'm.oneline': 'Deflect {n} meteors with one line',
  'm.chain': 'Destroy {n} meteors in one chain',
  'm.deflects': 'Deflect {n} meteors in total',
  'm.daily': 'Daily challenges played: {n}',

  'workshop.title': 'Workshop',
  'workshop.desc': 'Permanent upgrades that stay with you every run.',
  'workshop.max': 'MAX',
  'ws.ink': 'Deep Inkwell',
  'ws.ink.d': 'Ink capacity +12',
  'ws.regen': 'Steady Hand',
  'ws.regen.d': 'Ink refill +8%',
  'ws.dome': 'Solid Ground',
  'ws.dome.d': 'Start with +1 dome charge',
  'ws.reroll': 'Lucky Pen',
  'ws.reroll.d': '+1 power reroll per run',
  'ws.coin': 'Purse',
  'ws.coin.d': 'Gold earned +10%',
  'ws.golden': 'Gold Radar',
  'ws.golden.d': 'Golden meteors appear more often',
  'ws.start': 'Calligrapher Start',
  'ws.start.d': 'Begin with a rare power (Lv. 2: epic)',

  'pens.title': 'Pens',
  'pens.desc': 'Pick your ink color. Some unlock only with rank.',
  'pen.turkuaz': 'Turquoise',
  'pen.lale': 'Tulip',
  'pen.safran': 'Saffron',
  'pen.zumrut': 'Emerald',
  'pen.menekse': 'Violet',
  'pen.ates': 'Fire',
  'pen.buz': 'Ice',
  'pen.gokkusagi': 'Rainbow',
  'pens.equip': 'Use',
  'pens.equipped': 'In use',
  'pens.needRank': 'Needs {rank}',

  'records.title': 'Records',
  'records.empty': 'No records yet. Play your first run!',
  'records.top': 'Top 10 runs',
  'records.stats': 'Stats',
  'st.runs': 'Runs',
  'st.kills': 'Meteors destroyed',
  'st.wave': 'Best wave',
  'st.combo': 'Best combo',
  'st.boss': 'Red Giants defeated',
  'st.time': 'Time played',
  'st.daily': 'daily',

  'settings.title': 'Settings',
  'settings.music': 'Music',
  'settings.sfx': 'Sound effects',
  'settings.haptics': 'Vibration',
  'settings.quality': 'Graphics',
  'q.high': 'High',
  'q.balanced': 'Balanced',
  'q.saver': 'Battery saver',
  'settings.lang': 'Language',
  'lang.auto': 'Auto',
  'settings.fps': 'FPS counter',
  'settings.tutorial': 'Replay tutorial',
  'settings.reset': 'Reset progress',
  'settings.resetConfirm': 'Sure? Tap again to erase',
  'settings.resetDone': 'Progress reset',
  'settings.fullscreen': 'Fullscreen',
  'settings.credits': 'Ink Shield · version {v}',

  'tut.0': 'Drag your finger to draw a line under the meteor',
  'tut.1': 'Bounce the meteor into the other one: both explode',
  'tut.2': 'Ink is limited, watch the bar at the top. You are ready!',
  'tut.skip': 'Skip tutorial',

  'common.back': 'Back',
  'common.close': 'Close',
  'common.on': 'On',
  'common.off': 'Off',
  'common.min': '{m} min',
  'common.hm': '{h}h {m}m',
  'toast.record': 'New record!',
});
